# -*- coding: utf-8 -*-
"""diginext.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Mo3BUrF0XBu1N-dpg9icUbT-4Vv7TC9C

**1**
"""

def repeatStr(str,n,letter='a'):
  new_Str=str*n
  result=new_Str[:n] 
  num_Str=result.count(letter)
  txt = 'there are {} {} in your String'.format(num_Str,letter)
  print(txt)
  return  result

"""**2**"""

def decussate(Str='A'):
  num_remove=0
  Str = Str.upper()
  for i in range(len(Str)-1):
    if Str[i]==Str[i+1]:
      num_remove+=1
  return num_remove

"""**3**"""

def minSwap(arr):
    n = len(arr)
    arrpos = [*enumerate(arr)] 
    arrpos.sort(key=lambda it: it[1]) 
    vis= {k: False for k in range(n)} 
    
    num_swap = 0
    for i in range(n):
        if vis[i] or arrpos[i][0] == i:
            continue
        cycle_size = 0
        j = i
        while not vis[j]: 
            vis[j] = True
            j = arrpos[j][0]
            cycle_size += 1 
        if cycle_size > 0:
            num_swap += (cycle_size - 1)
 
    return num_swap